version: '2'
volumes:
  orderer1.orderer.com:
  orderer2.orderer.com:
  orderer3.orderer.com:
  peer1.deliverer.com:
  peer1.manufacturer.com:
  peer1.producer.com:
  peer1.retailer.com:
networks:
  fabric:
services:
  orderer1.orderer.com:
    hostname: orderer1.orderer.com
    image: hyperledger/fabric-orderer:2.2.2
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/cacerts/localhost-8054.pem]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./ordererOrganizations/orderer.com/orderer1/msp:/var/hyperledger/orderer/msp
      - ./ordererOrganizations/orderer.com/orderer1/tls:/var/hyperledger/orderer/tls
      - orderer1.orderer.com:/var/hyperledger/production/orderer
    networks:
      fabric:
        aliases:
          - orderer1.orderer.com
  orderer2.orderer.com:
    hostname: orderer2.orderer.com
    image: hyperledger/fabric-orderer:2.2.2
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/cacerts/localhost-8054.pem]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./ordererOrganizations/orderer.com/orderer2/msp:/var/hyperledger/orderer/msp
      - ./ordererOrganizations/orderer.com/orderer2/tls:/var/hyperledger/orderer/tls
      - orderer2.orderer.com:/var/hyperledger/production/orderer
    networks:
      fabric:
        aliases:
          - orderer2.orderer.com     
  orderer3.orderer.com:
    hostname: orderer3.orderer.com
    image: hyperledger/fabric-orderer:2.2.2
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/signcerts/cert.pem
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/keystore/server.key
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/cacerts/localhost-8054.pem]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./ordererOrganizations/orderer.com/orderer3/msp:/var/hyperledger/orderer/msp
      - ./ordererOrganizations/orderer.com/orderer3/tls:/var/hyperledger/orderer/tls
      - orderer3.orderer.com:/var/hyperledger/production/orderer
    networks:
      fabric:
        aliases:
          - orderer3.orderer.com  
  peer1.deliverer.com:
    container_name: peer1.deliverer.com
    hostname: peer1.deliverer.com
    image: hyperledger/fabric-peer:2.2.2     
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/cacerts/localhost-8054.pem
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer1.deliverer.com
      - CORE_PEER_ADDRESS=peer1.deliverer.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=pee1.deliverer.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052              
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=pee1.deliverer.com:7051
      - CORE_PEER_LOCALMSPID=DelivererMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./peerOrganizations/deliverer.com/peer1/msp:/etc/hyperledger/fabric/msp
      - ./peerOrganizations/deliverer.com/peer1/tls:/etc/hyperledger/fabric/tls
      - peer1.deliverer.com:/var/hyperledger/production
    networks:
      fabric:
        aliases:
          - peer1.deliverer.com
  peer1.manufacturer.com:
    container_name: peer1.manufacturer.com
    hostname: peer1.manufacturer.com
    image: hyperledger/fabric-peer:2.2.2     
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/cacerts/localhost-8054.pem
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer1.manufacturer.com
      - CORE_PEER_ADDRESS=peer1.manufacturer.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=pee1.manufacturer.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052              
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=pee1.manufacturer.com:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./peerOrganizations/manufacturer.com/peer1/msp:/etc/hyperledger/fabric/msp
      - ./peerOrganizations/manufacturer.com/peer1/tls:/etc/hyperledger/fabric/tls
      - peer1.manufacturer.com:/var/hyperledger/production
    networks:
      fabric:
        aliases:
          - peer1.manufacturer.com
  peer1.producer.com:
    container_name: peer1.producer.com
    hostname: peer1.producer.com
    image: hyperledger/fabric-peer:2.2.2     
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/cacerts/localhost-8054.pem
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer1.producer.com
      - CORE_PEER_ADDRESS=peer1.producer.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=pee1.producer.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052              
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=pee1.producer.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./peerOrganizations/producer.com/peer1/msp:/etc/hyperledger/fabric/msp
      - ./peerOrganizations/producer.com/peer1/tls:/etc/hyperledger/fabric/tls
      - peer1.producer.com:/var/hyperledger/production
    networks:
      fabric:
        aliases:
          - peer1.producer.com
  peer1.retailer.com:
    container_name: peer1.retailer.com
    hostname: peer1.retailer.com
    image: hyperledger/fabric-peer:2.2.2     
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/cacerts/localhost-8054.pem
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer1.retailer.com
      - CORE_PEER_ADDRESS=peer1.retailer.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=pee1.retailer.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052              
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=pee1.retailer.com:7051
      - CORE_PEER_LOCALMSPID=RetailerMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./peerOrganizations/retailer.com/peer1/msp:/etc/hyperledger/fabric/msp
      - ./peerOrganizations/retailer.com/peer1/tls:/etc/hyperledger/fabric/tls
      - peer1.retailer.com:/var/hyperledger/production
    networks:
      fabric:
        aliases:
          - peer1.retailer.com                          
  cli: 
    container_name: cli
    image: hyperledger/fabric-tools:2.2.2
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.producer.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
      - CORE_PEER_TLS_ENABLED=true
     # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.com/peers/peer1.producer.com/tls/server.crt
     # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.com/peers/peer1.producer.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/producer.com/msp/tlscacerts/server.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/producer.com/peer1/msp/user/admin/
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./peerOrganizations/producer.com/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/producer.com/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      fabric:  

